config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    
  root to: "introductions#index"
  
  resources :subjects do
    collection do
      get 'search'
    end
  end

  resources :publics, only: [:index, :create, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :students

  resources :users, only: [:index, :show] do
    resources :attendances
    collection do
      post 'check'
    end
  end
  
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user

    validates :grade, :class_number, :number, :name, :user, presence: true
    validates :class_number, numericality: { only_integer: true }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    
    def index
        @students = Student.where(user_id: current_user.id).page(params[:page]).per(50)
    end

    def show

    end

    def new
        @student = Student.new()
    end

    def create
        @student = Student.new(student_params)

        # エクセルファイルがアップロードされたときの処理
        if params[:student].try(:[], :file)
            student_registration
            redirect_to students_path
            flash[:notice] = "登録が完了しました。"
        # 手動で入力されたときの処理
        elsif @student.save
            redirect_to students_path
            flash[:notice] = "登録が完了しました。"
        else
            render :new
        end
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        if @student.update(student_params)
            flash[:notice] = "更新しました。"
            redirect_to(students_path)
        else
            render :edit
        end
    end

    def destroy
        Student.find(params[:id]).destroy
        flash[:notice] = "削除しました。"
        redirect_to students_path
    end

    private
    def student_params
        params.require(:student).permit(:grade, :class_number, :number, :name).merge(user_id: current_user.id)
    end

    def student_registration
        require 'roo'

        # ファイルのパスを取得
        file = params[:student][:file]
        temp_file = file.tempfile.path

        if File.extname(file.original_filename) != '.xlsx'
            flash[:error] = 'アップロードされたファイルは.xlsx形式である必要があります'
            redirect_to new_student_path and return
        end

        # エクセルファイルの読み取り
        excel = Roo::Excelx.new(temp_file)
        begin
            sheet = excel.sheet('sheet1')
        rescue Roo::NoSuchSheet
            flash[:error] = '「sheet1」という名前のシートが見つかりません'
            redirect_to new_student_path and return
        end
        rows = sheet.parse(grade: "grade", class_number: "class", number: "number", name: "name")

        # 読み取った情報からデータベースに登録
        rows.each do |row|
            Student.create(grade: row[:grade], class_number: row[:class_number], number: row[:number], name: row[:name], user_id: current_user.id)
        end

        # 一時ファイルの削除
        File.delete(temp_file)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/certificate.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="p-2 text-black-50 fs-1 text-center fw-bold mb-4">認証ページ</div>
    </div>  
  </div>
</div>

<% if ["存在しない学校idです", "学校idとメールアドレスが一致しません"].include?(flash[:notice]) %>
    <div class="bg-orange text-center fs-4 col-5 mx-auto">
        <span class="align-middle text-primary"><%= flash[:notice] %></span>
    </div>
<% end %>

<%= form_with(url: check_students_path, class: "row g-3 d-flex flex-column col-5 mx-auto", local: true) do |f| %>

  <div class="col-12">
    <%= f.label :user_id, "学校 id" %><br />
    <%= f.text_field :user_id, autofocus: true, class: "form-control" %>
  </div>

  <div class="col-12">
    <%= f.label :email, "学校メールアドレス" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="col-12 d-grid text-center">
    <%= f.submit "出欠席登録ページへ", class: "btn btn-primary" %>
  </div>

<% end %>

<div class="text-center">
  <%= link_to("ホーム", root_path, class: "btn btn-secondary mt-5 col-4 text-center") %>
</div>

app/views/students/edit.html.erb
<div class="bg-container">
  <%= render("shared/header") %>
  <div class="bg-image"></div>

  <div class="container py-3 mb-4">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="p-2 text-white fs-1 text-center fw-bold page-title">生徒情報編集</div>
      </div>  
    </div>
  </div>
</div>


<%= form_with(model: @student, class: "row g-3 mx-auto justify-content-center px-5", local: true) do |f| %>

    <div class="col-9">
        <%= f.label :grade, "学年" %><br />
        <%= f.text_field :grade, class: "form-control" %>
    </div>

    <div class="col-9">
        <%= f.label :class_number, "クラス" %><br />
        <%= f.text_field :class_number, class: "form-control" %>
    </div>

    <div class="col-9">
        <%= f.label :number, "番号" %><br />
        <%= f.text_field :number, class: "form-control" %>
    </div>

    <div class="col-9">
        <%= f.label :name, "氏名" %><br />
        <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="col-5 d-grid p-3">
        <%= f.submit "更新する", class: "btn btn-primary btn-lg p-3" %>
    </div>
<% end %>

app/views/students/index.html.erb
<div class="bg-container">
  <%= render("shared/header") %>
  <div class="bg-image"></div>

  <div class="container py-3 mb-4">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="p-2 text-white fs-1 text-center fw-bold page-title">生徒一覧</div>
      </div>  
    </div>
  </div>
</div>

<% if ["登録が完了しました。", "削除しました。", "更新しました。"].include?(flash[:notice]) %>
    <div class="bg-orange text-center fs-4 col-9 py-1 mx-auto mt-4">
        <span class="align-middle text-primary"><%= flash[:notice] %></span>
    </div>
<% end %>

<div class="table-wrapper" id="sort_table">
    <div class="links"><%=link_to("新規登録", new_student_path, class: "text-decoration-none") %></div>
    <table class="table table-striped  table-bordered text-center">
        <tr class="bg-dark-gray">
            <th class="fw-bold text-white"><i class="bi bi-sort-down fs-5 me-1 text-white"></i>ID</th>
            <th class="fw-bold text-white"><i class="bi bi-sort-down fs-5 me-1 text-white"></i>学年</th>
            <th class="fw-bold text-white"><i class="bi bi-sort-down fs-5 me-1 text-white"></i>クラス</th>
            <th class="fw-bold text-white"><i class="bi bi-sort-down fs-5 me-1 text-white"></i>番号</th>
            <th class="fw-bold text-white"><i class="bi bi-sort-down fs-5 me-1 text-white"></i>氏名</th>
            <th class="fw-bold text-white">アクション</th>
        </tr>
        <% @students.each do |student| %>
            <tr>
                <td><%= student.id %></td>
                <td><%= student.grade %></td>
                <td><%= student.class_number %></td>
                <td><%= student.number %></td>
                <td><%= student.name %></td>
                <td class="actions"><%=link_to("編集", edit_student_path(student.id), class: "text-decoration-none") %> | <%=link_to("削除", student_path(student.id), method: :delete, data:{confirm:"本当に削除しますか？"}, class: "text-decoration-none") %></td>
            </tr>
        <% end %>
    </table>
    <div class="mb-5">
      <%= paginate @students, window: 2 %>
    </div>
</div>

app/views/students/new.html.erb
<div class="bg-container">
  <%= render("shared/header") %>
  <div class="bg-image"></div>

  <div class="container py-3 mb-4">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="p-2 text-white fs-1 text-center fw-bold page-title">生徒登録</div>
      </div>  
    </div>
  </div>
</div>

<% if flash[:error] %>
    <div class="bg-orange text-center fs-4 col-9 py-1 mx-auto mt-4">
        <span class="align-middle text-primary"><%= flash[:error] %></span>
    </div>
<% end %>

<div class="container pt-2">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="p-2 fs-4 text-center fw-bold mb-1"><i class="bi bi-file-earmark-arrow-up"></i> ファイルをアップロードして登録</div>
    </div>  
  </div>
</div>
<div class="mx-auto image-block mb-3">
    <div class="attention mx-auto">
        <p class="my-1"><i class="bi bi-exclamation-circle"></i> アップロードできるファイルは「.xlsx」のみです</p>
        <p class="my-1"><i class="bi bi-exclamation-circle"></i> シート名は「sheet1」にしてください</p>
        <p class="my-1"><i class="bi bi-exclamation-circle"></i> 画像と同じカラム名で作成してください</p>
    </div>
    <%= image_tag("student_registration_sample.png", class: "sample_image")%>
</div>
<%= form_with(model: @student, class: "row col-5 mx-auto d-flex flex-column", local: true) do |f| %>

    <div class="form-group col-12 mb-3">
        <%= f.file_field :file, onchange: 'previewImage()', class: 'form-control' %>
        <%= f.hidden_field :avatar_cache %>
    </div>

    <div class="col-5 mx-auto text-center">
        <%= f.submit "登録する", class: "btn btn-primary p-2" %>
    </div>

<% end %>

<div class="container pt-2 mt-5">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="p-2 fs-4 text-center fw-bold mb-1"><i class="bi bi-keyboard fs-3"></i> 手動で入力</div>
    </div>  
  </div>
</div>
<%= form_with(model: @student, class: "row g-3 mx-auto justify-content-center px-5 col-8", local: true) do |f| %>

    <div class="col-sm-4">
        <%= f.label :grade, "学年" %><br />
        <%= f.text_field :grade, class: "form-control" %>
    </div>

    <div class="col-sm-4">
        <%= f.label :class_number, "クラス" %><br />
        <%= f.text_field :class_number, class: "form-control" %>
    </div>

    <div class="col-sm-4">
        <%= f.label :number, "番号" %><br />
        <%= f.text_field :number, class: "form-control" %>
    </div>

    <div class="col-12">
        <%= f.label :name, "氏名" %><br />
        <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="col-5 text-center">
        <%= f.submit "登録する", class: "btn btn-primary p-2" %>
    </div>
<% end %>