config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    
  root to: "introductions#index"
  
  resources :subjects do
    collection do
      get 'search'
    end
  end

  resources :publics, only: [:index, :create, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :students

  resources :users, only: [:index, :show] do
    resources :attendances
    collection do
      post 'check'
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :school, presence: true
  has_many :subjects, dependent: :destroy
  has_many :publics, dependent: :destroy
  has_many :students, dependent: :destroy
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    def after_sign_up_path_for(resource)
      subjects_path
    end
end
  

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def after_sign_in_path_for(resource)
      # ログイン後に遷移するページのパスを返します
      subjects_path
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index

    end

    def check
        user = User.find_by(id: params[:user_id])
        if user.nil?
            flash[:notice] = "存在しない学校idです"
            render :index
        elsif user.email == params[:email]
            redirect_to user_path(params[:user_id])
        else
            flash[:notice] = "学校idとメールアドレスが一致しません"
            render :index
        end
    end
    
    def show
        @attendances = Attendance.where(user_id: params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="header2 mb-4">
  <%= image_tag("carousel1.png") %>
  <div class="header2-absolute">
    <%= render("shared/header") %>
  </div>
  <div class="header2-title">
    <div class="p-2 text-white fs-1 text-center fw-bold page-title">出欠登録</div>
  </div>  
</div>

<% if ["存在しない学校idです", "学校idとメールアドレスが一致しません"].include?(flash[:notice]) %>
    <div class="bg-orange text-center fs-4 col-5 mx-auto">
        <span class="align-middle text-primary"><%= flash[:notice] %></span>
    </div>
<% end %>

<%= form_with(url: check_users_path, class: "row g-3 d-flex flex-column col-5 mx-auto", local: true) do |f| %>

  <div class="col-12">
    <%= f.label :user_id, "学校 id" %><br />
    <%= f.text_field :user_id, autofocus: true, class: "form-control" %>
  </div>

  <div class="col-12">
    <%= f.label :email, "学校メールアドレス" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="col-12 d-grid text-center">
    <%= f.submit "出欠席登録ページへ", class: "btn btn-primary" %>
  </div>

<% end %>

<div class="text-center">
  <%= link_to("ホーム", root_path, class: "btn btn-secondary mt-5 col-4 text-center") %>
</div>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <div class="bg-container">
    <%= render("shared/header") %>
    <div class="bg-image"></div>

    <div class="container py-3 mb-4">
      <div class="row justify-content-center">
        <div class="col-8">
          <div class="p-2 text-white fs-1 text-center fw-bold page-title"><%= current_user.school %>出欠登録</div>
        </div>  
      </div>
    </div>
  </div>
<% else %>
  <div class="header2 mb-4">
    <%= image_tag("carousel1.png") %>
    <div class="header2-absolute">
      <%= render("shared/header") %>
    </div>
    <div class="header2-title">
      <div class="p-2 text-white fs-1 text-center fw-bold page-title"><%= User.find(params[:id]).school %> 出欠登録</div>
    </div>  
  </div>
<% end %>

<% if ["登録しました", "全ての欄を入力してください", "無効な生徒IDです"].include?(flash[:notice]) %>
    <div class="bg-orange text-center fs-4 col-7 mx-auto mb-4">
        <span class="align-middle text-primary"><%= flash[:notice] %></span>
    </div>
<% end %>

<div class="row col-11 mx-auto justify-content-between">
  <%# フォーム %>
  <%= form_with( url: user_attendances_path(params[:id]), mothod: :post, local: true, class: "col-lg-4 col-8 mx-auto") do |f| %>
    <%= f.hidden_field :user_id, value: params[:id] %>
    
    <div class="col-12 mb-3">
        <%= f.label :student_id, "生徒id" %>
        <%= f.text_field :student_id, class: "form-control" %>
    </div> 
    <div class="col-12 mb-3">
      <%= f.label :status, "出欠席を登録" %>
      <select name="status" class="form-select form-control" aria-label="Default select example">
          <option selected>選択してください</option>
          <option value="欠席">欠席</option>
          <option value="遅刻">遅刻</option>
          <option value="早退">早退</option>
          <option value="公欠">公欠</option>
          <option value="忌引き">忌引き</option>
          <option value="その他">その他</option>
      </select>
    </div>
    <div class="col-12 mb-3">
        <%= f.label :start_time, "日付" %>
        <%= f.date_field :start_time, class: "form-control" %>
    </div>
    <div class="col-12 mb-3">
        <%= f.label :reason, "理由" %>
        <%= f.text_field :reason, class: "form-control", style: "height: 100px" %>
    </div>
    <div class="col-12 text-center mb-5">
        <%= f.submit "出欠を登録", class: "btn btn-primary col-6" %>
    </div>
  <% end %>
  
  <%# カレンダー %>
  <div class="col-lg-8 col-12 ps-lg-5">
    <%= week_calendar events: @attendances do |date, attendances| %>
      <div class="text-center p-1 mb-3 date-days">
        <%= date.day %>
      </div>
      <%# Statusの数値を更新 %>
      <% status_1, status_2, status_3, status_4, status_5, status_6 = 0, 0, 0, 0, 0, 0 %>
      <% attendances.each do |attendance| %>
        <% status_1 += 1 if attendance.status == "欠席" %>
        <% status_2 += 1 if attendance.status == "遅刻" %>
        <% status_3 += 1 if attendance.status == "早退" %>
        <% status_4 += 1 if attendance.status == "公欠" %>
        <% status_5 += 1 if attendance.status == "忌引き" %>
        <% status_6 += 1 if attendance.status == "その他" %>
      <% end %>
        <div>
          <p class="status-number <%= 'status-true' if status_1 != 0 %>">欠：<%= status_1 %>件</p>
          <p class="status-number <%= 'status-true' if status_2 != 0 %>">遅：<%= status_2 %>件</p>
          <p class="status-number <%= 'status-true' if status_3 != 0 %>">早：<%= status_3 %>件</p>
          <p class="status-number <%= 'status-true' if status_4 != 0 %>">公：<%= status_4 %>件</p>
          <p class="status-number <%= 'status-true' if status_5 != 0 %>">忌：<%= status_5 %>件</p>
          <p class="status-number <%= 'status-true' if status_6 != 0 %>">他：<%= status_6 %>件</p>
          <%= render(partial: "shared/modal", locals: {attendances: attendances, date: date}) if user_signed_in? %>
        </div>
    <% end %>
    <% if user_signed_in? %>
        <div class="text-end"><%= link_to("出欠一覧", user_attendances_path(current_user.id), class: "text-decoration-none") %></div>
    <% end %>
  </div>
</div>

<% if user_signed_in?%>
  <div class="row col-11 mx-auto chartkick mb-3">
    <div class="col-xl-6 col-9 mx-auto">
      <%= line_chart [
        { name: "欠席数", data: @attendances.where(status: "欠席").group_by_day(:start_time).count },
        { name: "遅刻数", data: @attendances.where(status: "遅刻").group_by_day(:start_time).count }
      ] , title: "欠席数・遅刻数の推移" %>
    </div>
    <div class="col-xl-6 col-9 mx-auto">
      <% grade_1, grade_2, grade_3, grade_4, grade_5, grade_6 = 0, 0, 0, 0, 0, 0 %>
      <% @attendances.each do |attendance| %>
        <% grade_1 += 1 if attendance.student.grade == 1 %>
        <% grade_2 += 1 if attendance.student.grade == 2 %>
        <% grade_3 += 1 if attendance.student.grade == 3 %>
        <% grade_4 += 1 if attendance.student.grade == 4 %>
        <% grade_5 += 1 if attendance.student.grade == 5 %>
        <% grade_6 += 1 if attendance.student.grade == 6 %>
      <% end %>
      <%= pie_chart [["1年生", grade_1], ["2年生", grade_2], ["3年生", grade_3], ["4年生", grade_4], ["5年生", grade_5], ["6年生", grade_6]],
       title: "学年別割合", colors: ["#FFB6C1", "#87CEEB", "#90EE90", "#FABC05", "#F0F0F0", "#3366CC"] %>
    </div>
    <div class="col-6 mx-auto mt-5">
      <%= column_chart Attendance.where(user_id: current_user.id).group_by_day_of_week(:start_time).count %>
    </div>
  </div>
<% end %>