config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    
  root to: "introductions#index"
  
  resources :subjects do
    collection do
      get 'search'
    end
  end

  resources :publics, only: [:index, :create, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :students

  resources :users, only: [:index, :show] do
    resources :attendances
    collection do
      post 'check'
    end
  end
  
end

app/views/shared/_card.html.erb
<div class="card">
  <div class="card-header">
    <%= subject.user.school %>
  </div>
  <div class="card-body">
    <div class="col-10 mt-1">教科 : <%= ChooseSubject.find(subject.subject_id).name %></div>
    <div class="col-10 mt-1">科目 : <%= subject.sub_subject %></div>
    <div class="col-10 mt-1">学年 : <%= subject.grade.name %></div>
    <div class="col-10 mb-4">実施 : <%= subject.month.name %></div>
    <h5 class="card-title mb-2"><%= subject.title %></h5>
    <div class="card-text subject-content mb-4"><%= subject.content %></div>
    <% if subject.file.file %>
        <% file_path = subject.file.file.file %>
        <p class="mb-1">添付ファイル</p>
        <%= link_to("#{subject.file.file.original_filename}", subject.file.url, class: "mb-2") %>
    <% end %>
    <% if controller_name == 'subjects' %>
      <div class="d-flex mt-4">
        <%= link_to("詳細", subject_path(subject.id), class: "btn btn-light text-secondary text-decoration-none border-secondary me-1") %>
        <%= link_to("編集", edit_subject_path(subject.id), class: "btn btn-light text-secondary text-decoration-none border-secondary me-1") %>
        <%= link_to("削除", subject_path(subject.id), method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-light text-danger text-decoration-none border-secondary") %>
      </div>
    <% else %>
      <div class="d-flex mt-4">
        <%= link_to("詳細", subject_path(subject.id), class: "btn btn-light text-secondary text-decoration-none border-secondary me-1") %>
      </div>
    <% end %>
  </div>
  <div class="card-footer text-muted d-flex justify-content-between">
    <div><%= l subject.created_at %></div>
    <div>投稿者：<%= subject.name %></div>
  </div>
  <% if controller_name == 'subjects' %>
    <div class="card-footer text-muted d-flex justify-content-center">   
        <div id="public_buttons_<%= subject.id %>" class="">
            <%= render(partial: "shared/public_button", locals: {subject: subject}, class: "align-middle") %>
        </div>
    </div>
  <% end %>
  
</div>

app/views/shared/_contents.html.erb
<div class="container mt-5">
    <div class="row g-3">
        <% @subjects.each do |subject| %>
            <% if controller_name == 'subjects' && subject.user_id == current_user.id %>
                <div class="col-xl-4 col-md-6">
                    <div class="service card-effect scroll_up">                    
                        <%= render(partial: "shared/card", locals: {subject: subject}) %>
                    </div>
                </div>
            <% end %>

            <% if controller_name == 'publics' %>
                <div class="col-xl-4 col-md-6" >
                    <div class="service card-effect public-card scroll_up">
                        <%= render(partial: "shared/card", locals: {subject: subject}) %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg main-header navbar-dark px-5 py-3 sticky-top">
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to("Education Log", subjects_path, class: "text-secondary navbar-brand fs-4 header-logo me-5") %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        <ul class="navbar-nav ms-4 mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-secondary" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                投稿
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item"><%= link_to("新規投稿", new_subject_path, class: "nav-link fs-6 dropdown-item text-secondary") %></li>
              <li class="nav-item"><%= link_to("ユーザーの投稿", subjects_path, class: "nav-link fs-6 dropdown-item text-secondary") %></li>
              <li class="nav-item"><%= link_to("公開されている投稿", publics_path, class: "nav-link fs-6 dropdown-item text-secondary") %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-secondary" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              生徒管理
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item"><%= link_to("生徒一覧", students_path, class: "nav-link fs-6 dropdown-item text-secondary") %></li>
              <li class="nav-item"><%= link_to("生徒登録", new_student_path, class: "nav-link fs-6 dropdown-item text-secondary") %></li>
              <li class="nav-item"><%= link_to("出欠一覧", user_path(current_user.id), class: "nav-link fs-6 dropdown-item text-secondary") %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-secondary" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              ユーザー管理
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item"><%= link_to("ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしてよろしいですか？" }, class: "nav-link fs-6 dropdown-item text-secondary") %></li>
              <li class="nav-item"><%= link_to("アカウント編集・退会", edit_user_registration_path, class: "nav-link fs-6 dropdown-item text-secondary") %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ms-4 mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to("Education Log", root_path, class: "text-secondary navbar-brand fs-4 header-logo me-5") %>
          <li class="nav-item">
            <%= link_to("ログイン", new_user_session_path, class: "nav-link fs-6 text-secondary") %>
          </li>
          <li class="nav-item">
            <%= link_to("新規登録", new_user_registration_path, class: "nav-link fs-6 text-secondary") %>
          </li>
          <li class="nav-item">
            <%= link_to("公開されている投稿", publics_path, class: "nav-link fs-6 dropdown-item text-secondary") %>
          </li>
        </ul>
      <% end %>
      <% if controller_name == 'subjects' %>
        <%= form_with(url: search_subjects_path, local: true, method: :get, class: "d-flex") do |f| %>
          <%= f.text_field :keyword, placeholder: "KEY WORD", class: "form-control me-2 bg-light me-4 text-center", type: "search" %>
          <%= f.submit "検索", class: "btn btn-light"%>
        <% end %>
      <% end %>
      <% if controller_name == 'publics' %>
        <%= form_with(url: search_publics_path, local: true, method: :get, class: "d-flex") do |f| %>
          <%= f.text_field :keyword, placeholder: "KEY WORD", class: "form-control me-2 bg-light me-4 text-center", type: "search" %>
          <%= f.submit "検索", class: "btn btn-light"%>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_modal.html.erb
<!-- Button trigger modal -->
<div class="d-flex justify-content-center">
    <button type="button" class="btn btn-light text-secondary border-secondary mx-auto" data-bs-toggle="modal" data-bs-target="#exampleModal<%=date.day%>">
        詳細
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal<%=date.day%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-daialog-scrollable">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><%= date.month %>月<%= date.day %>日</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <% attendances.each do |attendance| %>
            <div class="modal-attendance p-3 mb-3 border">
                <p class="mb-1"><%= attendance.student.grade %>年
                <%= attendance.student.class_number %>組
                <%= attendance.student.number %>番
                <%= attendance.student.name %></p>
                <div class="d-flex">
                    <div class="me-2"><%= attendance.status%>の理由 :</div>
                    <div><%= attendance.reason %></div>
                </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
        </div>
        </div>
    </div>
    </div>
</div>

app/views/shared/_new_edit.html.erb
<%= form_with(model: @subject, class: "row g-3 mx-auto justify-content-center px-5", local: true) do |f| %>
  <%= render "shared/error_messages", model: @subject %>

  <div class="col-9">
    <%= f.label :subject_id, "教科" %><br />
    <%= f.collection_select(:subject_id, ChooseSubject.all, :id, :name, {}, {class:"form-select form-control"}) %>
  </div>

  <div class="col-9">
    <%= f.label :sub_subject, "科目" %><br />
    <%= f.text_field :sub_subject, class: "form-control" %>
  </div>

  <div class="col-9">
    <%= f.label :title, "単元・タイトル" %><br />
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="col-9">
    <%= f.label :month_id, "授業実施月" %><br />
    <%= f.collection_select(:month_id, Month.all, :id, :name, {}, {class:"form-select form-control"}) %>
  </div>

  <div class="col-9">
    <%= f.label :grade_id, "対象学年" %><br />
    <%= f.collection_select(:grade_id, Grade.all, :id, :name, {}, {class:"form-select form-control"}) %>
  </div>

  <div class="col-9">
    <%= f.label :name, "投稿者名" %><br />
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="col-9">
    <%= f.label :content, "授業の流れ・生徒の様子" %><br />
    <%= f.text_area :content, class: "form-control", rows: "5" %>
  </div>

  <div class="form-group col-9">
    <%= f.label :file ,"授業用資料"%>
    <%= f.file_field :file, onchange: 'previewImage()', class: 'form-control' %>
    <%= f.hidden_field :avatar_cache %>
  </div>

  <div class="col-5 d-grid p-3">
    <%= f.submit "投稿する", class: "btn btn-primary btn-lg p-3" %>
  </div>
<% end %>

app/views/shared/_public_button.html.erb
<% if Public.where(subject_id: subject.id).exists? %>
    <div class="d-flex justify-content-center">
        <span class="text-secondary text-decoration-none me-2">非公開</span>
        <%= link_to(public_path(subject.public.id), method: :delete, class: "align-middle", remote: true) do %>
            <div class="form-check form-switch">
                <input class="form-check-input public-button public-button-checked" type="checkbox" id="flexSwitchCheckDefault" checked>
                <label class="form-check-label" for="flexSwitchCheckDefault"></label>
            </div>
        <% end %>
        <span class="text-secondary text-decoration-none">公開</span>
    </div>
<% else%>
    <div class="d-flex justify-content-center">
        <span class="text-secondary text-decoration-none me-2">非公開</span>
            <%= link_to(publics_path(user_id: current_user.id, subject_id: subject.id), method: :post, remote: true) do %>
                <div class="form-check form-switch">
                    <input class="form-check-input public-button public-button-unchecked" type="checkbox" id="flexSwitchCheckDefault">
                    <label class="form-check-label" for="flexSwitchCheckDefault"></label>
                </div>
            <% end %>
        <span class="text-secondary text-decoration-none">公開</span>
    </div>
<% end %>